name: Release Workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          
      - name: Install goreleaser
        run: |
         curl -sL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | bash -s -- -b /usr/local/bin/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Get GitHub release tag
        id: get_tag
        run: echo "::set-output name=tag::${{ github.ref }}"

      - name: Build and push Docker image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/super_calculator:${DOCKER_IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/super_calculator:${DOCKER_IMAGE_TAG}
